### ISSUE TITLE
Problem with Load URL 

### ISSUE THREAD

**Issue by w452tr4w5etgre** [dfaker/WebmGenerator#62]
When I use the Load URL button and enter the link to a YouTube video two clips are added but neither work.
Trying to load the URL again works as normal, as it's from the version stored in the temp folder.
This happens nearly every time, sometimes the top clip works as normal on the first download.

Video of the issue: https://files.catbox.moe/pvjqd0.mp4

Log:
```
2022-03-01 01:33:04,884 [Thread-5    ] [ERROR]  Image worker Exception
Traceback (most recent call last):
  File "C:\WebmGenerator-win64\src\ffmpegService.py", line 74, in imageWorker
    videoInfo = getVideoInfo(cleanFilenameForFfmpeg(filename))
  File "C:\WebmGenerator-win64\src\encodingUtils.py", line 31, in cleanFilenameForFfmpeg
    return getShortPathName(os.path.normpath(filename))
pywintypes.error: (2, 'GetShortPathNameW', 'The system cannot find the file specified.')
2022-03-01 01:33:05,385 [Thread-4    ] [ERROR]  Image worker Exception
Traceback (most recent call last):
  File "C:\WebmGenerator-win64\src\ffmpegService.py", line 74, in imageWorker
    videoInfo = getVideoInfo(cleanFilenameForFfmpeg(filename))
  File "C:\WebmGenerator-win64\src\encodingUtils.py", line 31, in cleanFilenameForFfmpeg
    return getShortPathName(os.path.normpath(filename))
pywintypes.error: (2, 'GetShortPathNameW', 'The system cannot find the file specified.')

```

**Comment by dfaker** [comment]
Reworked in most recent release
