### ISSUE TITLE
Getting FileNotFoundError for some reason

### ISSUE THREAD

**Issue by asr1191** [dfaker/WebmGenerator#67]
I've been getting this error for some reason. It was working fine till now. I don't remember making any changes to break something. I've attached part of the log below. Full logs here: https://pastebin.com/gii55L5M

```
Complete Pass 1 Encode Pass 2  ed_1.mp4 0.75
2022-03-24 17:16:38,113 [Thread-6    ] [ERROR]  unhandled CONCAT exception
Traceback (most recent call last):
  File "K:\WebmGenerator\src\ffmpegService.py", line 1004, in encodeWorker
  File "K:\WebmGenerator\src\ffmpegService.py", line 973, in encodeConcat
  File "K:\WebmGenerator\src\encoders\mp4x264Encoder.py", line 133, in encoder
  File "K:\WebmGenerator\src\optimisers\linear.py", line 31, in encodeTargetingSize
  File "K:\WebmGenerator\src\encoders\mp4x264Encoder.py", line 124, in encoderFunction
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'tempVideoFiles\\ed_1.mp4'
```

**Comment by asr1191** [comment]
I realised that this happens when I set "Directly Copy Source" in the Audio Channels settings. If I set it another one, there's no error.

**Comment by dfaker** [comment]
Thanks asr1191, yeah there's a bug with the "Directly Copy Source" if there are any filters applied to the clip, there's a fix for some of the use cases of "Directly Copy Source" coming in the next release but for some things it's straight going to have to be disabled.
