### ISSUE TITLE
Stopped working after 3.31

### ISSUE THREAD

**Issue by plissken1138** [dfaker/WebmGenerator#93]
Fails to open.

Debug info:
===================================================
2023-01-16 06:30:49,512 [MainThread  ] [INFO ]  Startup.
2023-01-16 06:30:50,867 [MainThread  ] [ERROR]  Startup Exception
Traceback (most recent call last):
  File "webmGenerator.py", line 29, in <module>
  File "K:\WebmGenerator\src\webmGeneratorController.py", line 39, in <module>
  File "K:\WebmGenerator\src\cutselectionUi.py", line 16, in <module>
  File "K:\WebmGenerator\src\modalWindows.py", line 36, in <module>
  File "C:\Users\baxter001\AppData\Local\Programs\Python\Python310\lib\site-packages\mpv.py", line 39, in <module>
  File "C:\Users\baxter001\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed
2023-01-16 06:30:50,870 [MainThread  ] [ERROR]  Traceback (most recent call last):
  File "webmGenerator.py", line 29, in <module>
  File "K:\WebmGenerator\src\webmGeneratorController.py", line 39, in <module>
  File "K:\WebmGenerator\src\cutselectionUi.py", line 16, in <module>
  File "K:\WebmGenerator\src\modalWindows.py", line 36, in <module>
  File "C:\Users\baxter001\AppData\Local\Programs\Python\Python310\lib\site-packages\mpv.py", line 39, in <module>
  File "C:\Users\baxter001\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed

2023-01-16 06:30:50,873 [MainThread  ] [INFO ]  DONE
===================================================

3.31 is the latest that works. 
Win10Edu x64 21H2

**Comment by 30secstf** [comment]
Same here on a system with Win10Pro and an old AMD Phenom cpu. Another system with same Win10Pro and a Xeon E3 1220 v3 Haswell cpu works just fine with v3.34.0

Also, encoding a clip with VP9 10bpp gives very low values of PSNR, same clip encoded in VP9 gives 10 points more. Bitrates, file size and visual are different for the two files but very near. This is true for both v3.33.0 and v3.34.0

**Comment by dfaker** [comment]
> encoding a clip with VP9 10bpp gives very low values of PSNR

The different bit depths change the "quality" meaning of a specific PSNR value, I'll see about redefinition of the 'quality' ranges for other bit depths.

**Comment by 30secstf** [comment]
> Simply replace the DLL in the program folder.

For me this works, thanks! 

Not sure if this the right place to ask but I have problems dealing with exporting projects and filters. I do the editing and the encoding on two different systems and while subclips loads more or less fine (sometimes they are slighly shifted by few frames, it is noticeable because of the scene change and I have to manually shift the subclip) but filters aren't loaded at all. 
Also it would be useful if WebmGenerator would search for the video source in the same folder as the .webgproj file first, regardless of the path.

**Comment by dfaker** [comment]
Release 3.34.0 re-built with that dll: https://github.com/dfaker/WebmGenerator/releases/tag/v3.34.0
@plissken1138 please confirm this works for you too and I'll close this.

**Comment by dfaker** [comment]
> is it possible for WebmGenerator to run with ffmpeg and yt-dlp that are already placed in PATH rather than having separate ones in WebmGenerator directory?

Yes that should work, it's simply extending the path with the working dir at the moment so the global version should equally happily be used.
