### ISSUE TITLE
ModuleNotFoundError: No module named 'pathvalidate'

### ISSUE THREAD

**Issue by broconut123** [dfaker/WebmGenerator#97]
3.36 gives this error on linux. 3.35 works. 
Also I'm unable to drag and drop files into the program like it works on windows and instead have to use the very basic file picker which is a bit annoying to use. When drag and dropping it will drop the file to what program is active behind the webmgenerator window.

~/WebmGenerator master ?13 ❯ python webmGenerator.py
Initial working directory /home/x/WebmGenerator
Current working directory /home/x/WebmGenerator
2023-03-02 19:18:00,664 [MainThread  ] [INFO ]  Startup.
/home/x/WebmGenerator/src
/usr/bin
module 'os' has no attribute 'add_dll_directory'
No module named 'tkinterdnd2'
2023-03-02 19:18:00,695 [MainThread  ] [ERROR]  win32api getShortPathName Exception
Traceback (most recent call last):
  File "/home/x/WebmGenerator/src/encodingUtils.py", line 26, in <module>
    import win32api
ModuleNotFoundError: No module named 'win32api'
/home/x/WebmGenerator/src
/usr/bin
module 'os' has no attribute 'add_dll_directory'
2023-03-02 19:18:00,923 [MainThread  ] [ERROR]  Startup Exception
Traceback (most recent call last):
  File "/home/x/WebmGenerator/webmGenerator.py", line 29, in <module>
    from src.webmGeneratorController import WebmGeneratorController
  File "/home/x/WebmGenerator/src/webmGeneratorController.py", line 41, in <module>
    from .mergeSelectionUi import MergeSelectionUi
  File "/home/x/WebmGenerator/src/mergeSelectionUi.py", line 3, in <module>
    from pathvalidate import sanitize_filepath
ModuleNotFoundError: No module named 'pathvalidate'
2023-03-02 19:18:00,923 [MainThread  ] [ERROR]  Traceback (most recent call last):
  File "/home/x/WebmGenerator/webmGenerator.py", line 29, in <module>
    from src.webmGeneratorController import WebmGeneratorController
  File "/home/x/WebmGenerator/src/webmGeneratorController.py", line 41, in <module>
    from .mergeSelectionUi import MergeSelectionUi
  File "/home/x/WebmGenerator/src/mergeSelectionUi.py", line 3, in <module>
    from pathvalidate import sanitize_filepath
ModuleNotFoundError: No module named 'pathvalidate'
'

**Comment by dfaker** [comment]
Main readme now updated with `pathvalidate` and `tkinterdnd2` dependecies which should solve both of your issues.
