### ISSUE TITLE
hwaccel nvenc

### ISSUE THREAD

**Issue by sintaxx** [dfaker/WebmGenerator#98]
i'm running latest version of WebMGenerator, Latest nvidia drivers and Windows 11

last couple versions if webmg have not worked with hwaccel for some reason, i've even tried running as administrator..

```
b'\r\n-vsync is deprecated. Use -fps_mode'
b'\r\n[mov,mp4,m4a,3gp,3g2,mj2 @ 000001be1aa157c0] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!'
b'\r\n[mov,mp4,m4a,3gp,3g2,mj2 @ 000001be1aa157c0] moov atom not found'
b'\r\ntempVideoFiles\\0_Cable_management_masters-937114294003795UNILAD1f96_0.0_181.53471624266146_740a6e0db7_1682450655_1.mp4: Invalid data found when processing input'
Encode Failed Pass 1 Encode Pass 2  Cable-management-masters-937114294003795-UNILAD-1-f967651387702044v-1_4.mp4 1
Complete Pass 1 Encode Pass 2  Cable-management-masters-937114294003795-UNILAD-1-f967651387702044v-1_4.mp4 0.75
2023-04-25 15:31:30,977 [Thread-6 (en] [ERROR]  unhandled CONCAT exception
Traceback (most recent call last):
  File "K:\WebmGenerator\src\ffmpegService.py", line 1314, in encodeWorker
  File "K:\WebmGenerator\src\ffmpegService.py", line 1283, in encodeConcat
  File "K:\WebmGenerator\src\encoders\mp4x264NvencEncoder.py", line 155, in encoder
  File "K:\WebmGenerator\src\optimisers\linear.py", line 54, in encodeTargetingSize
  File "K:\WebmGenerator\src\encoders\mp4x264NvencEncoder.py", line 145, in encoderFunction
```

**Comment by dfaker** [comment]
I assume this is is a x624 mp4? can you try disabling `nvEncIntermediateFiles` in properties?
Otherwise please share the source video url you're grabbing for this.

**Comment by sintaxx** [comment]
i don't have the URL anymore but i disabled nvEncIntermediateFiles and now it seems to work just fine

**Comment by dfaker** [comment]
Added a check to confirm if nvenc is possible before running it now, it will fall-back to the non-accelerated version if not supported.
